#!/usr/bin/env node
/* V20 independent UI smoke tests. Read-only. No browser or live orders. */
'use strict';
const assert=require('node:assert/strict'), fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const h=read('preview/rebuild-v20/index.html');
const css=read('preview/rebuild-v20/site.css');
const source=read('preview/rebuild-v20/engine.js');
let checked=0;
const ok=(condition,message)=>{checked++;assert.ok(condition,message);console.log('PASS '+message)};
ok(!/styles-v17-safe\.css/.test(h),'No previous CSS stylesheet imported');
ok(!/preview\/v20\/skin\.css/.test(h),'No layered v20 CSS imported');
ok(h.includes('href="/preview/rebuild-v20/site.css?v=1"'),'Brand-new stylesheet linked');
ok(h.includes('src="/preview/rebuild-v20/engine.js?v=1"'),'Dedicated commerce adapter linked');
ok(h.includes('<base href="../../">'),'Preview products resolve to root assets');
ok(h.includes('content="noindex,nofollow"'),'Preview hidden from search indexing');
ok(h.includes('SELECT_SHOP_TEST_MODE=true'),'Production tracking disabled before script');
ok(!/src="meta-pixel\.js/.test(h),'No production Meta Pixel script in preview');
ok(h.includes('stopImmediatePropagation();notice()'),'Order forms blocked by capture-phase preview guard');
ok(source.includes('selectShopCartRebuildV20Preview'),'Isolated cart storage key');
ok(source.includes('selectShopRebuildV20PreviewLastOrder'),'Isolated last-order key');
ok(source.includes('new URL(\`/preview/rebuild-v20/?product='),'Product deep-link remains in preview');
ok(source.includes('const SHOP_WHATSAPP_NUMBER'),'Real merchant order code kept but sends guarded');
ok(source.includes('function renderCart()'),'Original robust cart renderer retained');
ok(source.includes('function commitSheetItem()'),'Cart commit handler retained');
ok(source.includes('function selectSheetVariant('),'Color selection maintained');
ok(source.includes('function renderSizes()'),'Size filtering maintained');
ok(source.includes('tryToggle.addEventListener("click"'),'Two-size toggle remains bound');
ok(source.includes('function calcTotals('),'Supplier-independent existing calculator retained');
ok(source.includes('function checkoutMessage('),'WhatsApp order formatter retained');
ok(source.includes('function renderCatalog('),'Product cards generated from data');
ok(source.includes('product.variants.map((item, thumbIndex) =>'),'Every color thumbnail rendered');
ok(css.includes('object-fit:contain'),'Shoes displayed with contain, not global cover');
ok(css.includes('.cart-item-tools'),'Cart edit/remove buttons newly styled');
ok(css.includes('.cart-add-actions'),'Second model picker newly styled');
ok(css.includes('.size-btn.active'),'Selected sizes newly styled');
ok(css.includes('@media(max-width:700px)'),'Dedicated mobile layout');
ok((css.match(/\{/g)||[]).length===(css.match(/\}/g)||[]).length,'CSS balanced');
new vm.Script(source,{filename:'engine.js'});ok(true,'Commerce engine JavaScript parses');
const allId=[...h.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
ok(new Set(allId).size===allId.length,'No duplicate DOM IDs');
const required=['modelRail','cartCount','dockCartCount','heroBuy','heroProductImage','productSheet','cartSheet','checkoutSheet','checkoutForm','sheetBackdrop','sheetBuyNow','sheetAddCart','variantRail','sizeRail','trySizeToggle','cartList','cartSummary','cartCheckout','whatsappFallback','dockBuy','toast','productLightbox','checkoutItems','checkoutSavings','previewBlockedToast'];
for(const id of required)ok(allId.includes(id),'Required functional node #'+id);
const start=source.indexOf('const CONFIG =');
const stop=source.indexOf('window.SELECT_SHOP_PRODUCTS =');
ok(start>0 && stop>start,'Shared product catalog located');
const data=vm.runInNewContext(source.slice(start,stop)+'\n({CONFIG,PRODUCTS});',{});
const ps=Object.values(data.PRODUCTS), vs=ps.flatMap(p=>p.variants);
ok(ps.length===4,'4 sneaker families');
ok(vs.length===19,'19 sneaker color combinations');
ok(vs.every(v=>Array.isArray(v.sizes)&&v.sizes.length>0),'Every color has valid available sizes');
for(const family of ps){ok(fs.existsSync(path.join(root,'product',family.id,'index.html')),'Existing family route '+family.id);for(const v of family.variants){ok(fs.existsSync(path.join(root,'product',v.id,'index.html')),'Existing direct variant route '+v.id)}}
const first=source.indexOf('function calcTotals('), last=source.indexOf('const roleLabel =');
ok(last>first,'Calculator source located');
const calculator=vm.runInNewContext(source.slice(first,last)+'\ncalcTotals;',{PRODUCTS:data.PRODUCTS,CONFIG:data.CONFIG});
const one=[{id:'a',productId:'alex',role:'primary',sizes:[41,42]}];
const two=[...one,{id:'b',productId:'wk',role:'trial',sizes:[38]}];
const bought=[...one,{id:'b',productId:'wk',role:'purchase',sizes:[38]}];
let a=calculator(one),b=calculator(two),c=calculator(bought);
ok(a.pairCount===1 && a.total===data.PRODUCTS.alex.price,'Try-two-sizes treated as ONE paid pair');
ok(b.pairCount===1&&b.trialCount===1&&b.total===data.PRODUCTS.alex.price,'Trial secondary model adds zero payable amount');
ok(c.pairCount===2&&c.total===data.PRODUCTS.alex.price+data.PRODUCTS.wk.price-data.CONFIG.SHIPPING_FEE,'Two purchased models apply EXACTLY one shipping saving');
ok(c.shippingSaving===data.CONFIG.SHIPPING_FEE,'Discount equals shipping saving, not fabricated');
ok(new Set(vs.map(x=>x.id)).size===19,'Color slug IDs unique');
ok(h.includes('href="#carCare"') && !h.includes('href="product/carwash48/"'),'Car-care navigation stays in rebuild preview');
ok(!h.includes('href="./"'),'No drawer home link leaks to original site');
ok(!h.includes('<script src="script-v17-safe.js'),'Never import old production JS directly');
console.log('V20 Rebuild preflight PASSED: '+checked+' checks. Browser and image review still required.');
